name: "Ubuntu CI workflow"


on:
  push:
    branches: [ dev ]
  #schedule:
      #- cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  

jobs:

  ubuntu-job:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  

  ubuntu-1604-job:
    name: "ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  

  ubuntu-1804-job:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
      
#https://docs.librenms.org/Installation/Install-LibreNMS/
  ubuntu-2004-job:
    name: "ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Install Required Packages"
      run: sudo apt-get install -qqy software-properties-common   
      
#https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
  ubuntu-2004-nagios-job:
    name: "ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Prerequisites 1"
      run: sudo dpkg -l selinux*    
    - name: "Prerequisites 2"
      #This guide is based on SELinux being disabled or in permissive mode. SELinux is not enabled by default on Ubuntu
      run: sudo dpkg -l selinux*
    - run: |
        sudo dpkg -l selinux*
        sudo apt-get update -qq
        sudo apt-get install -yqq autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.4 libgd-dev
      name: Build and Test
    - name: "Prerequisites"
      run: |
        sudo dpkg -l selinux*
        sudo apt-get update -qq
        sudo apt-get install -yqq autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.4 libgd-dev
           
        
